services:
  web:
    image: nginx:stable-alpine3.21-perl
    container_name: nginx
    volumes:
      - ./docker/development/nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - .:/usr/share/nginx/html
      - node_modules:/usr/share/nginx/html/node_modules
      - vendor:/usr/share/nginx/html/vendor
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - docker-network
  vite:
    build:
      context: .
      dockerfile: ./docker/development/vite/Dockerfile
    image: laravel-react-typeracer-vite-dev:1.0
    container_name: vite
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - vendor:/app/vendor
    networks:
      - docker-network
    env_file:
      - .env
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: red6660320/laravel-react-typeracer-dev:1.0
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
      - node_modules:/usr/share/nginx/html/node_modules
      - vendor:/usr/share/nginx/html/vendor
    networks:
      - docker-network
    ports:
      - 9000:9000
    depends_on:
      - db
    env_file:
      - .env
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: laravel-react-typeracer-queue-worker-dev:1.0
    container_name: queue-worker
    restart: unless-stopped
    command: ['/bin/bash', '-c', '/usr/local/bin/wait-for-ready.sh php artisan queue:work']
    volumes:
      - .:/usr/share/nginx/html
      - node_modules:/usr/share/nginx/html/node_modules
      - vendor:/usr/share/nginx/html/vendor
    environment:
      - IS_WORKER=true
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - app
      - redis
  db:
    image: postgres:17.5
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/dev
    ports:
      - 5433:5432
    volumes:
      - app-data-dev:/var/lib/postgresql/data
    networks:
      - docker-network
    env_file:
      - .env
  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data-dev:/data
    networks:
      - docker-network
    env_file:
      - .env
  reverb:
    image: red6660320/laravel-react-typeracer-dev:1.0
    container_name: reverb
    networks:
      - docker-network
    ports:
      - 8080:8080
    depends_on:
      - app
    volumes:
      - app-data-dev:/usr/share/nginx/html
    env_file:
      - .env
    environment:
      - IS_WORKER=true
      - SKIP_FIX_PERMS=1
    command: ['/bin/bash', '-c', '/usr/local/bin/wait-for-ready.sh php artisan reverb:start']
volumes:
  app-data-dev:
    driver: local
  redis-data-dev:
    driver: local
  node_modules:
  vendor:
networks:
  docker-network:
    driver: bridge
