name: Create a Pull Request to master from staging

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          base: master
          title: 'Promote staging → master'
          body: 'Automated PR created after updates in staging'
          delete-branch: false
