name: Test Laravel with Pest and React with Playwright

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    services:
      redis:
        image: redis:latest
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo, pgsql, pdo_pgsql, redis
          tools: composer:v2

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.testing .env

      - name: Setup Cloudinary configuation
        run: |
          echo "" >> .env.testing
          echo "CLOUDINARY_URL=${{secrets.CLOUDINARY_URL}}" >> .env.testing
          echo "CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}}" >> .env.testing
          echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" >> .env.testing
          echo "CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}" >> .env.testing
          echo "CLOUDINARY_SECURE_URL=${{secrets.CLOUDINARY_SECURE_URL}}" >> .env.testing

      - name: Setup Reverb + Pusher config
        run: |
          {
            echo ""
            echo "REVERB_APP_ID=${{secrets.REVERB_APP_ID}}"
            echo "REVERB_APP_KEY=${{secrets.REVERB_APP_KEY}}"
            echo "REVERB_APP_SECRET=${{secrets.REVERB_APP_SECRET}}"
            echo "REVERB_HOST=${{secrets.REVERB_HOST}}"
            echo "REVERB_PORT=${{secrets.REVERB_PORT}}"
            echo "REVERB_SCHEME=${{secrets.REVERB_SCHEME}}"
            echo "VITE_REVERB_APP_KEY=${{secrets.VITE_REVERB_APP_KEY}}"
            echo "VITE_REVERB_HOST=${{secrets.VITE_REVERB_HOST}}"
            echo "VITE_REVERB_PORT=${{secrets.VITE_REVERB_PORT}}"
            echo "VITE_REVERB_SCHEME=${{secrets.VITE_REVERB_SCHEME}}"
            echo "PUSHER_APP_ID=${{secrets.REVERB_APP_ID}}"
            echo "PUSHER_APP_KEY=${{secrets.REVERB_APP_KEY}}"
            echo "PUSHER_APP_SECRET=${{secrets.REVERB_APP_SECRET}}"
          } >> .env

      - name: Show .env for debugging
        run: cat .env

      - name: Generate key
        run: php artisan key:generate --env=testing

      - name: Clear caches
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Run migrations
        run: php artisan migrate --force --env=testing

      - name: Install JS deps
        run: npm ci

      - name: Build assets
        run: npm run build

      # - name: Run Laravel tests
      #   run: php artisan test --coverage

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
